config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "links#index"

  resources :links, only: [:show, :new, :create] do
    resource :upvote, only: [:create]
    resource :downvote, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      resources :links, only: [:index, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ActiveRecord::Base
	validates :title, presence: true
  validates :url, presence: true
  before_create :initialize_upvotes_downvotes

  IMAGE_FORMATS = %w(.jpg .gif .png)

  def initialize_upvotes_downvotes
    self.upvotes = 0 unless upvotes.present?
    self.downvotes = 0 unless downvotes.present?
  end

  def upvote
  	increment!(:upvotes, 1)
  end

  def downvote
    increment!(:downvotes, 1)
  end

  def self.hottest_first
    order("upvotes - downvotes DESC")
  end

  def score
    Score.new(self)
  end

  def image?
    url.end_with? *IMAGE_FORMATS
  end
end

app/models/score.rb
class Score
  CONTROVERSIAL_THRESHOLD = 0.2

  attr_reader :upvotes, :downvotes

  def initialize(link)
    @upvotes = link.upvotes
    @downvotes = link.downvotes
  end

  def value
    upvotes - downvotes
  end

  def controversial?
    score_delta_percentage < CONTROVERSIAL_THRESHOLD
  end

  def ==(other)
    other.upvotes == upvotes && other.downvotes == downvotes
  end

  alias :eql? :==

  def hash
    [upvotes, downvotes].hash
  end

  private

  def score_delta_percentage
    score_delta.to_f / high_score
  end

  def high_score
    [upvotes, downvotes].max
  end

  def score_delta
    value.abs
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < Api::BaseController
  def index
    links = Link.hottest_first
    render json: links
  end

  def create
    link = Link.new(link_params)

    if link.save
      render json: link, status: :created
    else
      render json: { errors: link.errors.full_messages },
        status: :unprocessable_entity
    end
  end

  private

  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/downvotes_controller.rb
class DownvotesController < ApplicationController
  def create
    link = Link.find(params[:link_id])
    link.downvote

    redirect_to :back
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	def index
		@links = Link.hottest_first
	end

	def show
    @link = Link.find(params[:id])
  end

	def create
		@link = Link.new(link_params)

    if @link.save
    	LinkMailer.new_link(@link)
      redirect_to @link
    else
      render :new
    end
	end

	def new
		@link = Link.new
	end

	def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def create
    link = Link.find(params[:link_id])
    link.upvote

    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def formatted_score_for(score)
    "#{value(score)} (+#{score.upvotes}, -#{score.downvotes})"
  end

  private

  def value(score)
  	score.upvotes - score.downvotes
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTestingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_link.erb
<%= link_to link.url do %>
  <%= link.title %>

  <% if link.image? %>
    <%= image_tag link.url %>
  <% end %>
<% end %>

app/views/links/_link.html.erb
<%= link_to link.url do %>
  <%= link.title %>

  <% if link.image? %>
    <%= image_tag link.url %>
  <% end %>
<% end %>

app/views/links/_link_list.erb
<%= content_tag_for :li, link do %>
  <%= link_to "Upvote", [link, :upvote], method: :post %>
  <div data-role="score"><%= formatted_score_for(link.score) %></div>
  <%= link_to "Downvote", [link, :downvote], method: :post %>

  <%= render link %>
<% end %>

app/views/links/_link_list.html.erb
<%= content_tag_for :li, link do %>
  <%= link_to "Upvote", [link, :upvote], method: :post %>
  <div data-role="score"><%= formatted_score_for(link.score) %></div>
  <%= link_to "Downvote", [link, :downvote], method: :post %>

  <%= render link %>
<% end %>

app/views/links/index.html.erb
<div class="hold">
  <div class="header">
    <div class="container">
      <div id="logo"></div>
      <ul class="nav">
        <li><a href="#">Wow</a></li>
        <li><a href="#">Wow</a></li>
        <li><a href="#">Wow</a></li>
        <li><a href="#">Wow</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="section">
  <div class="slider">
    <div class="container slidercontent">
      <h1 class="hero">Wow</h1>
      <h2 class="hero">Wow.Wow.Wow</h2>
      <div class="call"><span>Wow</span></div>
    </div>
  </div>
</div>
<div class="section">
  <div class="container">
    <div class="col four">
      <h1 class="icon">[]</h1>
      <h1 class="service">Wow</h1>
      <p>Wow wow wow wow wow wow wow wow wow wow wow wow wow</p>
    </div>
    <div class="col four">
      <h1 class="icon">[]</h1>
      <h1 class="service">Wow</h1>
      <p>Wow wow wow wow wow wow wow wow wow</p>
    </div>
    <div class="responsivegroup"></div>
    <div class="col four">
      <h1 class="icon">[]</h1>
      <h1 class="service">Wow</h1>
      <p>Wow wow wow wow wow wow wow wow wow wow wow</p>
    </div>
    <div class="col four">
      <h1 class="icon">[]</h1>
      <h1 class="service">Wow</h1>
      <p>Wow wow wow wow wow wow wow</p>
    </div>
    <div class="group"></div>
  </div>
</div>
<div class="section bg">
  <div class="container">
    <h1>Wow wow</h1>
    <h2>Wow wow wow!</h2>
    <div class="col three bg nopad pointer">
      <div class="imgholder"></div>
      <h1 class="feature">Wow</h1>
      <p>Wow wow</p>
    </div>
    <div class="col three bg nopad pointer">
      <div class="imgholder"></div>
      <h1 class="feature">Wow</h1>
      <p>Wow wow wow</p>
    </div>
    <div class="col three bg nopad pointer">
      <div class="imgholder"></div>
      <h1 class="feature">Wow</h1>
      <p>Wow wow wow</p>
    </div>
    <div class="group margin"></div>
    <div class="col three bg nopad pointer">
      <div class="imgholder"></div>
      <h1 class="feature">Wow</h1>
      <p>Wow wow</p>
    </div>
    <div class="col three bg nopad pointer">
      <div class="imgholder"></div>
      <h1 class="feature">Wow</h1>
      <p>Wow wow wow</p>
    </div>
    <div class="col three bg nopad pointer">
      <div class="imgholder"></div>
      <h1 class="feature">Wow</h1>
      <p>Wow wow wow</p>
    </div>
    <div class="group"></div>
  </div>
</div>
<div class="section">
  <div class="container">
    <h1>Wow? Wow wow wow wow!</h1>
    <h2>Wow</h2>
    <div class="col three">
      <h1 class="icon side">[]</h1>
      <h1 class="feature side">Wow</h1>
      <p class="side">Wow wow wow wow wow wow wow wow wow wow wow wow wow</p>
    </div>
    <div class="col three">
      <h1 class="icon side">[]</h1>
      <h1 class="feature side">Wow</h1>
      <p class="side">Wow wow wow wow wow wow wow wow</p>
    </div>
    <div class="col three">
      <h1 class="icon side">[]</h1>
      <h1 class="feature side">Wow</h1>
      <p class="side">Wow wow wow wow wow wow wow wow wow wow wow</p>
    </div>
    <div class="group margin"></div>
    <div class="col three">
      <h1 class="icon side">[]</h1>
      <h1 class="feature side">Wow</h1>
      <p class="side">Wow wow wow wow wow wow wow</p>
    </div>
    <div class="col three">
      <h1 class="icon side">[]</h1>
      <h1 class="feature side">Wow</h1>
      <p class="side">Wow wow wow wow wow wow wow wow</p>
    </div>
    <div class="col three">
      <h1 class="icon side">[]</h1>
      <h1 class="feature side">Wow</h1>
      <p class="side">Wow wow wow wow wow wow wow wow</p>
    </div>
    <%= link_to "Submit a new link", new_link_path %>

    <ul id="links">
      <%= render partial: "links/link_list", collection: @links, as: :link %>
    </ul>
  </div>
</div>
<div class="section bg">
  <div class="container">
    <h1>Wow</h1>
    <h2>Wow wow wow wow</h2>
    <div class="col two bg margin extrapad">
      <h1 class="icon side">[]</h1>
      <span class="feature side">Wow</span
      ><span class="side"> - Wow wow wow</span>
      <p class="side">
        Wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow
        wow wow
      </p>
    </div>
    <div class="col two bg margin extrapad">
      <h1 class="icon side">[]</h1>
      <span class="feature side">Wow wow</span
      ><span class="side"> - Wow wow</span>
      <p class="side">
        Wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow
        wow wow wow wow wow
      </p>
    </div>
    <div class="group margin"></div>
    <div class="col two bg margin extrapad">
      <h1 class="icon side">[]</h1>
      <span class="feature side">Wow wow</span><span class="side"> - Wow</span>
      <p class="side">
        Wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow
      </p>
    </div>
    <div class="col two bg margin extrapad">
      <h1 class="icon side">[]</h1>
      <span class="feature side">Wow</span><span class="side"> - Wow wow</span>
      <p class="side">
        Wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow
        wow wow wow wow
      </p>
    </div>
    <div class="group"></div>
  </div>
</div>
<div class="section">
  <div class="container">
    <div class="col two">
      <h1 class="icon">[]</h1>
      <h1 class="service">Wow</h1>
      <p>Wow wow wow wow wow wow wow wow wow wow wow wow wow</p>
    </div>
    <div class="col two">
      <h1 class="icon">[]</h1>
      <h1 class="service">Wow</h1>
      <p>Wow wow wow wow wow wow wow wow wow</p>
    </div>
    <div class="group"></div>
  </div>
</div>
<div class="section">
  <div class="container">
    <h1 class="reset">Terrible.</h1>
  </div>
</div>
<div class="section">
  <div class="footer">
    <div class="container white">
      <div class="col four left">
        <h1>What?</h1>
        <p>
          So that's it. This started out as 20 minutes of making fun of modern
          web dev. Then it turned into a few hours of it.
        </p>
        <p>I hope you've enjoyed looking at every modern website ever.</p>
        <p>
          I don't actually hate this style as long as the content is meaningful.
          In fact, I think this type of design is pretty cool and effective.
        </p>
      </div>
      <div class="col four left">
        <h1>How?</h1>
        <p>
          CSS3 and HTML. JS for header shrinking; optional. Site works perfectly
          with JS disabled (another gripe of mine with modern web dev).
        </p>
        <p>Only external libraries are GFonts.</p>
        <p>Moderately responsive, should work on anything modern.</p>
      </div>
      <div class="col four left">
        <h1>Why?</h1>
        <p>
          Many popular HTML themes have thousands of lines of HTML, thousands of
          lines of CSS and several JS plugins on every page amounting to tens of
          thousands of lines of JavaScript.
        </p>
        <p>
          I fail to see a valid reason for this, particularly the horrendous
          line counts that are usually due to unused features or badly designed
          code.
        </p>
      </div>
      <div class="col four left">
        <h1>Who?</h1>
        <p>I'm Andrew.</p>
        <p>
          You can get in touch with me through
          <a href="http://atunnecliffe.com">http://atunnecliffe.com</a> or
          <a href="mailto:andrew@atunnecliffe.com">emailing me</a>.
        </p>
      </div>
      <div class="group"></div>
    </div>
  </div>
</div>

app/views/links/new.html.erb
<%= form_for @link do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <%= form.submit "Submit!" %>
<% end %>

app/views/links/show.html.erb
<%= render @link %>